### ISSUE TITLE
Use go tag to define the variables

### ISSUE THREAD

**Issue by davidebianchi** [mia-platform/configlib#22]
**Is your feature request related to a problem? Please describe.**
A common issue declaring the env vars is to not set correctly the name mapping between configuration and env struct

**Describe the solution you’d like**
We could change the lib to use the go tags in struct fields instead of the `configlib.EnvConfig` struct. In this way, with tags for required, the source env variable and so on.

**Additional context**

For example:

```go
type EnvironmentVariables struct {
	LogLevel       string `config:"variable=LOG_LEVEL,required"`
	HTTPPort       string `config:"variable=HTTP_PORT,required"`
}
```

**Comment by davidebianchi** [comment]
We could use a lib like https://github.com/caarlos0/env instead of the configlib, which should already handle the env in this way.
So, we could remove the env variable part of this lib.

**Comment by fredmaggiowski** [comment]
it is fine to me, we should start by deprecating the feature and then move to caarlos0 library

**Comment by davidebianchi** [comment]
Add the deprecation notice and link to the caarlos0 library. In the next major, we should remove the support.
